puts "The students of Villains academy"
puts "--------------------------------"
puts "Dr. Hanibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Curlione"
puts "Alex Delaege"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
